language: php

php:
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4

before_install:
  - composer update -n

script:
  - ./vendor/bin/phpcs -v --standard=PSR2 src tests/CrowdStar
  - ./vendor/bin/phpunit tests
